PresentationLayer/Areas/Admin/ViewModels/AddPensionerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PresentationLayer.Areas.Admin.ViewModels
{
    public class AddPensionerViewModel
    {
        //Data Like "Marital Status", "Gender", "Title" 
        public EditPersonalDetailsViewModel Pensioner { get; set; }

        //Origin Data Like "State", "Lga"
        public EditOriginDetailsViewModel OriginDetails { get; set; }

        //Employent Data Like "Last Employment"
        public EditEmploymentDetailsViewModel EmploymentDetails { get; set; }

        //Next Of Kin Details Like "Surname, OtherNames, Passport"
        public EditNextOfKinDetailsViewModel NextOfKinDetails { get; set; }

        //Bank Details Like: "Bank, BankBranch"
        public EditBankDetailsViewModel BankDetails { get; set; }
        
    }
}

PresentationLayer/Areas/Admin/Controllers/PensionerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PresentationLayer.Models;
using ModelLayer;
using BusinessLayer;
using PresentationLayer.Controllers;
using PresentationLayer.Areas.Admin.ViewModels;

namespace PresentationLayer.Areas.Admin.Controllers
{
    public class PensionerController : BaseController
    {
        // GET: Admin/Pensioner
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            ViewBag.Title = string.Format("Welcome {0} | View All Pensioners", DoesCookieExist("Username") ? GetHttpCookie("Username") : "Admin");
            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult ViewPensioners()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AddPensioner()
        {
            ViewBag.Title = string.Format("Add Pensioner | {0}", DoesCookieExist("Username") ? GetHttpCookie("Username") : "Admin");
            return View();
        }
        //Fill Select Options
        //BaseController: Upload File
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult AddPensioner(AddPensionerViewModel model)
        {
            try
            {              
                throw new Exception("Model Seems to work");
            }
            catch(Exception ex) { throw ex; }

            return View();
        }

        public ActionResult EmploymentData()
        {
            return View();
        }

        public ActionResult BankData()
        {
            return View();
        }

        public ActionResult OriginData()
        {
            return View();
        }

        public ActionResult PersonalData()
        {
            return View();
        }

        public ActionResult NextOfKinData()
        {
            return View();
        }

        public ActionResult EditPersonalData()
        {
            return View();
        }

        public ActionResult EditOriginData()
        {
            return View();
        }

        public ActionResult EditEmploymentData()
        {
            return View();
        }

        public ActionResult EditBankData()
        {
            return View();
        }

        public ActionResult EditNextOfKinData()
        {
            return View();
        }

        public ActionResult AllDetails()
        {
            return View();
        }

    }
}

PresentationLayer/Areas/Admin/Views/Pensioner/AllDetails.cshtml
@model PresentationLayer.Areas.Admin.ViewModels.ViewAllDetailsViewModel
@{
    ViewBag.Title = "AllDetails";
}

<div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2 box-shadow" style="margin-top:30px;margin-bottom: 20px;background:whitesmoke;padding: 20px 10px; box-shadow: 0 2px 4px 0 rgba(0,0,0,0.16),0 2px 10px 0 rgba(0,0,0,0.12)!important;">
        <h1  class="text-center text-info">All Details For <span class="text-danger">Chukwuma Ezeh</span></h1>

        <h3 class="text-center text-info">Personal Details For: Chukwuma Ezeh</h3>
        <div class="col-xs-12" style="background:#fff;padding:10px;">
            <ul>
                <li>
                    <img src="@Url.Content("~/Images/user_male.png")"
                         width="200"
                         height="200"
                         style="border:1px solid #ddd;"
                         class="img-circle img-responsive" />
                </li>
                <li style="font-size: 16px; padding: 20px 10px;"><span class="text-info">TITLE: </span> MR</li>
                <li style="font-size: 16px; padding: 20px 10px;"><span class="text-info">SURNAME: </span> EMMANUEL</li>
                <li style="font-size: 16px; padding: 20px 10px;"><span class="text-info">Other Name(s): </span> OKOYE P.</li>
                <li style="font-size: 16px; padding: 20px 10px;"><span class="text-info">GENDER: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">MARITAL STATUS: </span> 12/09/1009</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">SPOUSE: </span> Head Master</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">DATE ADDED: </span> 0918393030</li>
            </ul>
        </div>

        <h3 class="text-center text-info">Origin details</h3>
        <div class="col-xs-12" style="background:#fff;padding:10px;">
            <ul>
                <li style="font-size: 16px; padding: 20px 10px;"><span class="text-info">PHONE NUMBER: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">STATE: </span> Abia</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">HOME TOWN: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">LGA: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">NATIONALITY: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">HOME ADDRESS: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">DATE OF BIRTH: </span> 0918393030</li>
            </ul>
        </div>

        <h3 class="text-center text-info">Employment details</h3>
        <div class="col-xs-12" style="background:#fff;padding:10px;">
            <ul>
                <li style="font-size: 16px; padding: 20px 10px;"><span class="text-info">FIRST APPOINTMENT: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">LAST APPOINTMENT: </span> 12/09/1009</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">LAST POST: </span> Head Master</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">SERVICE LEVEL(AT RETIREMENT): </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">REASON FOR RETIREMENT: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">LENGTH OF SERVICE: </span> 0918393030</li>
            </ul>
        </div>

        <h3 class="text-center text-info">Next Of Kin Details</h3>
        <div class="col-xs-12" style="background:#fff;padding:10px;">
            <ul>
                <li>
                    <img src="@Url.Content("~/Images/user_male.png")"
                         width="200"
                         height="200"
                         style="border:1px solid #ddd;"
                         class="img-circle img-responsive" />
                </li>
                <li style="font-size: 16px; padding: 20px 10px;"><span class="text-info">SURNAME: </span> EMMANUEL</li>
                <li style="font-size: 16px; padding: 20px 10px;"><span class="text-info">SURNAME: </span> OKOYE P.</li>
                <li style="font-size: 16px; padding: 20px 10px;"><span class="text-info">PHONE NUMBER: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">RELATIONSHIP: </span> 12/09/1009</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">GENDER: </span> Head Master</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">HOME ADDRESS: </span> 0918393030</li>
            </ul>
        </div>

        <h3 class="text-center text-info">Bank details</h3>
        <div class="col-xs-12" style="background:#fff;padding:10px;">
            <ul>
                <li style="font-size: 16px; padding: 20px 10px;"><span class="text-info">BANK: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">BANK BRANCH: </span> 12/09/1009</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">ACCOUNT NUMBER: </span> Head Master</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">GROSS PENSION: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">DEDUCTIBLE: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">NET PENSION: </span> 0918393030</li>
            </ul>
        </div>

        <div class="col-xs-12" style="padding-top:15px;">
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <a href="@Url.Action("Index", "Pensioner")" class="btn btn-warning">Go Back</a>
                </div>
                <div class="col-xs-12 col-sm-6 text-right">
                    <a href="" class="btn btn-info">PRINT</a>
                </div>
            </div>
        </div>
    </div>
</div>

PresentationLayer/Areas/Admin/Views/Pensioner/BankData.cshtml
@{
    ViewBag.Title = "BankData";
}

<div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2 box-shadow" style="margin-top:30px;margin-bottom: 20px;background:whitesmoke;padding: 20px 10px; box-shadow: 0 2px 4px 0 rgba(0,0,0,0.16),0 2px 10px 0 rgba(0,0,0,0.12)!important;">
        <h3 class="text-center text-info">Bank details For: Chukwuma Ezeh</h3>
        <div class="col-xs-12" style="background:#fff;padding:10px;">
            <ul>
                <li style="font-size: 16px; padding: 20px 10px;"><span class="text-info">BANK: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">BANK BRANCH: </span> 12/09/1009</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">ACCOUNT NUMBER: </span> Head Master</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">GROSS PENSION: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">DEDUCTIBLE: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">NET PENSION: </span> 0918393030</li>
            </ul>
        </div>
        <div class="col-xs-12" style="padding-top:15px;">
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <a href="@Url.Action("Index", "Pensioner")" class="btn btn-warning">Go Back</a>
                </div>
                <div class="col-xs-12 col-sm-6 text-right">
                    <a href="" class="btn btn-info">PRINT</a>
                </div>
            </div>
        </div>
    </div>
</div>

PresentationLayer/Areas/Admin/Views/Pensioner/EditBankData.cshtml
@model PresentationLayer.Areas.Admin.ViewModels.EditBankDetailsViewModel
@{
    ViewBag.Title = "EditBankData";
}

<div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2 box-shadow" style="margin-top:30px;margin-bottom: 20px;background:whitesmoke;padding: 20px 10px; box-shadow: 0 2px 4px 0 rgba(0,0,0,0.16),0 2px 10px 0 rgba(0,0,0,0.12)!important;">
        <h3 class="text-center text-info">Edit Bank details For: Chukwuma Ezeh</h3>
        <div class="col-xs-12" style="background:#fff;padding:10px;">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    
                    <div class="form-group">
                        @Html.LabelFor(model => model.Bank, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select name="Bank" class="form-control">
                                <option>-- Select --</option>
                                <option value="1">Mr</option>
                                <option value="2">Mrs</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.Bank, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.BankBranch, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.BankBranch, new { htmlAttributes = new { @class = "form-control text-lowercase" } })
                            @Html.ValidationMessageFor(model => model.BankBranch, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.AccountNo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.AccountNo, new { htmlAttributes = new { @class = "form-control text-lowercase" } })
                            @Html.ValidationMessageFor(model => model.AccountNo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.GrossPension, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.GrossPension, new { htmlAttributes = new { @class = "form-control text-lowercase" } })
                            @Html.ValidationMessageFor(model => model.GrossPension, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Deductible, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Deductible, new { htmlAttributes = new { @class = "form-control text-lowercase" } })
                            @Html.ValidationMessageFor(model => model.Deductible, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Edit" class="btn btn-info btn-block" />
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="col-xs-12" style="padding-top:15px;">
            <div class="col-xs-12 col-sm-6">
                <a href="@Url.Action("Index", "Pensioner")" class="btn btn-warning">Go Back</a>
            </div>
        </div>
    </div>
</div>

PresentationLayer/Areas/Admin/Views/Pensioner/EditEmploymentData.cshtml
@model PresentationLayer.Areas.Admin.ViewModels.EditEmploymentDetailsViewModel
@{
    ViewBag.Title = "EditEmploymentData";
}

<div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2 box-shadow" style="margin-top:30px;margin-bottom: 20px;background:whitesmoke;padding: 20px 10px; box-shadow: 0 2px 4px 0 rgba(0,0,0,0.16),0 2px 10px 0 rgba(0,0,0,0.12)!important;">
        <h3 class="text-center text-info">Edit Employment details For: Chukwuma Ezeh</h3>
        <div class="col-xs-12" style="background:#fff;padding:10px;">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.DateOfFirstAppointment, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DateOfFirstAppointment, new { htmlAttributes = new { @class = "form-control text-lowercase" } })
                            @Html.ValidationMessageFor(model => model.DateOfFirstAppointment, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DateOfLastAppointment, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DateOfLastAppointment, new { htmlAttributes = new { @class = "form-control text-lowercase" } })
                            @Html.ValidationMessageFor(model => model.DateOfLastAppointment, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LastPost, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select name="LastPost" class="form-control">
                                <option>-- Select --</option>
                                <option value="1">Head Teacher</option>
                                <option value="2">Driver</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.LastPost, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.GradeAsAtRetirement, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select name="GradeAsAtRetirement" class="form-control">
                                <option>-- Select --</option>
                                <option value="1">Level One</option>
                                <option value="2">Driver</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.GradeAsAtRetirement, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.YearsInService, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.YearsInService, new { htmlAttributes = new { @class = "form-control text-lowercase" } })
                            @Html.ValidationMessageFor(model => model.YearsInService, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ReasonforRetirement, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select name="ReasonforRetirement" class="form-control">
                                <option>-- Select Gender --</option>
                                <option value="1">Male</option>
                                <option value="2">Female</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.ReasonforRetirement, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Edit" class="btn btn-info btn-block" />
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="col-xs-12" style="padding-top:15px;">
            <div class="col-xs-12 col-sm-6">
                <a href="@Url.Action("Index", "Pensioner")" class="btn btn-warning">Go Back</a>
            </div>
        </div>
    </div>
</div>

PresentationLayer/Areas/Admin/Views/Pensioner/EditNextOfKinData.cshtml
@model PresentationLayer.Areas.Admin.ViewModels.EditNextOfKinDetailsViewModel
@{
    ViewBag.Title = "EditNextOfKinData";
}

<div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2 box-shadow" style="margin-top:30px;margin-bottom: 20px;background:whitesmoke;padding: 20px 10px; box-shadow: 0 2px 4px 0 rgba(0,0,0,0.16),0 2px 10px 0 rgba(0,0,0,0.12)!important;">
        <h3 class="text-center text-info">Edit Next Of Kin details For: Chukwuma Ezeh</h3>
        <div class="col-xs-12" style="background:#fff;padding:10px;">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" name="ImageFile" />
                            @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })

                            <input type="hidden" value="" name="PensionerId"/>
                            <input type="hidden" value="" name="NOkId"/>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select name="Gender" class="form-control">
                                <option>-- Select --</option>
                                <option value="1">Male</option>
                                <option value="2">Female</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control text-lowercase" } })
                            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.OtherNames, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.OtherNames, new { htmlAttributes = new { @class = "form-control text-lowercase" } })
                            @Html.ValidationMessageFor(model => model.OtherNames, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select name="Gender" class="form-control">
                                <option>-- Select Gender --</option>
                                <option value="1">Male</option>
                                <option value="2">Female</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Relationship, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select name="Relationship" class="form-control">
                                <option>-- Select Relationship --</option>
                                <option value="1">Son</option>
                                <option value="2">Mother</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.Relationship, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control text-lowercase" } })
                            @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PermenentHouseAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PermenentHouseAddress, new { htmlAttributes = new { @class = "form-control text-lowercase" } })
                            @Html.ValidationMessageFor(model => model.PermenentHouseAddress, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Edit" class="btn btn-info btn-block" />
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="col-xs-12" style="padding-top:15px;">
            <div class="col-xs-12 col-sm-6">
                <a href="@Url.Action("Index", "Pensioner")" class="btn btn-warning">Go Back</a>
            </div>
        </div>
    </div>
</div>

PresentationLayer/Areas/Admin/Views/Pensioner/EmploymentData.cshtml
@{
    ViewBag.Title = "EmploymentData";
}
<div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2 box-shadow" style="margin-top:30px;margin-bottom: 20px;background:whitesmoke;padding: 20px 10px; box-shadow: 0 2px 4px 0 rgba(0,0,0,0.16),0 2px 10px 0 rgba(0,0,0,0.12)!important;">
        <h3 class="text-center text-info">Employment details For: Chukwuma Ezeh</h3>
        <div class="col-xs-12" style="background:#fff;padding:10px;">
            <ul>
                <li style="font-size: 16px; padding: 20px 10px;"><span class="text-info">FIRST APPOINTMENT: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">LAST APPOINTMENT: </span> 12/09/1009</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">LAST POST: </span> Head Master</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">SERVICE LEVEL(AT RETIREMENT): </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">REASON FOR RETIREMENT: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">LENGTH OF SERVICE: </span> 0918393030</li>
            </ul>
        </div>
        <div class="col-xs-12" style="padding-top:15px;">
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <a href="@Url.Action("Index", "Pensioner")" class="btn btn-warning">Go Back</a>
                </div>
                <div class="col-xs-12 col-sm-6 text-right">
                    <a href="" class="btn btn-info">PRINT</a>
                </div>
            </div>
        </div>
    </div>
</div>

PresentationLayer/Areas/Admin/Views/Pensioner/NextOfKinData.cshtml
@{
    ViewBag.Title = "NextOfKinData";
}

<div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2 box-shadow" style="margin-top:30px;margin-bottom: 20px;background:whitesmoke;padding: 20px 10px; box-shadow: 0 2px 4px 0 rgba(0,0,0,0.16),0 2px 10px 0 rgba(0,0,0,0.12)!important;">
        <h3 class="text-center text-info">Next Of Kin Details For: Chukwuma Ezeh</h3>
        <div class="col-xs-12" style="background:#fff;padding:10px;">
            <ul>
                <li>
                    <img src="@Url.Content("~/Images/user_male.png")" 
                         width="200" 
                         height="200" 
                         style="border:1px solid #ddd;" 
                         class="img-circle img-responsive"/>
                </li>
                <li style="font-size: 16px; padding: 20px 10px;"><span class="text-info">SURNAME: </span> EMMANUEL</li>
                <li style="font-size: 16px; padding: 20px 10px;"><span class="text-info">SURNAME: </span> OKOYE P.</li>
                <li style="font-size: 16px; padding: 20px 10px;"><span class="text-info">PHONE NUMBER: </span> 0918393030</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">RELATIONSHIP: </span> 12/09/1009</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">GENDER: </span> Head Master</li>
                <li style="font-size: 16px;padding: 20px 10px;"><span class="text-info">HOME ADDRESS: </span> 0918393030</li>
            </ul>
        </div>
        <div class="col-xs-12" style="padding-top:15px;">
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <a href="@Url.Action("Index", "Pensioner")" class="btn btn-warning">Go Back</a>
                </div>
                <div class="col-xs-12 col-sm-6 text-right">
                    <a href="" class="btn btn-info">PRINT</a>
                </div>
            </div>
        </div>
    </div>
</div>