PresentationLayer/Areas/Admin/Controllers/ManageAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PresentationLayer.Models;
using PresentationLayer.Controllers;
using ModelLayer.Model;
using BusinessLayer;
using System.Web.Routing;

namespace PresentationLayer.Areas.Admin.Controllers
{
    public class ManageAccountController : BaseController
    {
        private UserLogic userLogic;
        private UserRolesLogic userRolesLogic;

        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);;
        }

        public ManageAccountController()
        {
            userLogic = new UserLogic();
            userRolesLogic = new UserRolesLogic();

           
        }

        // GET: Admin/ManageAccount
        [Authorize(Roles = "Admin")]
        public ActionResult Index()//For changing an user's details
        {

            try
            {
                ViewBag.Title = string.Format("Change Your Account Credentials | {0}", GetHttpCookie("Username"));

                //Patch the form values in           
                ChangePasswordVieWModel ChangeDetails = new ChangePasswordVieWModel();

                if (DoesCookieExist("Username") && DoesCookieExist("Password"))
                {
                    ChangeDetails.Username = GetHttpCookie("Username");
                    ChangeDetails.Password = GetHttpCookie("Password");
                    ChangeDetails.ConfirmPassword = GetHttpCookie("Password");
                    ChangeDetails.UserId = GetHttpCookiesAsInt("UserId");
                    ChangeDetails.UserRole = GetHttpCookiesAsInt("UserRole");
                   
                    return View(ChangeDetails);
                }

            }
            catch(Exception ex) { throw ex; }

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Index(ChangePasswordVieWModel model)
        {
            try
            {
                //Patch the userId saved as a cookie into the model
                model.UserId = Int32.Parse(GetHttpCookie("UserId"));

                if (ModelState.IsValid)
                {
                    var translatedRoles = userRolesLogic.GetModelBy(ur => ur.id == model.UserRole);
                    var similarUser = userLogic.CountEntityForCondition(u => u.username == model.Username && u.password == model.Password);

                    if (similarUser > 0)
                    {
                        throw new Exception("These Credentials already exist");
                    }
                    //update the db with these details
                    userLogic.Update(new User()
                    {
                        Id = model.UserId,//Reset this field after sorting out issue with Login-in
                        Username = model.Username,
                        Password = model.ConfirmPassword,
                        Role = translatedRoles
                    });

                    //Reset the cookies found in the browser
                    SetHttpCookies("Username", model.Username);
                    SetHttpCookies("Password", model.Password);

                    return RedirectToAction("Index", "Pensioner", new { Area = "Admin" });
                }
            }
            catch(Exception ex)
            {
                SetMessage(string.Format("Error Occured! {0}", ex.Message), Message.Category.Error);
                throw ex;
            }
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AddNewAdmin()//For registering a new user
        {
            try
            {
                ViewBag.Title = string.Format("Add New Admin | {0}", GetHttpCookie("Username"));
                PopulateUserRolesField();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult AddNewAdmin(RegisterViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var translatedRole = userRolesLogic.GetModelBy(ur => ur.id == model.Role);
                    //Get a single userModel from the DB
                    var similarModel = userLogic.CountEntityForCondition(u => u.username == model.Username && u.password == model.Password);

                    if(similarModel > 0)
                    {
                        throw new Exception("These Credentials already exist");                      
                    }

                    userLogic.Create(new User()
                    {
                        Username = model.Username,
                        Password = model.ConfirmPassword,
                        Role = translatedRole
                    });

                    return RedirectToAction("Index", "Pensioner", new { area = "Admin" });
                }
            }
            catch(Exception ex)
            {
                SetMessage(string.Format("Error Occured! {0}", ex.Message), Message.Category.Error);
                throw ex;
            }
            return View(model);
        }

        private void PopulateUserRolesField()
        {
            var userRoles = userRolesLogic.GetKeyValuePairs();
            if (userRoles != null && userRoles.Count > 0)
            {
                ViewBag.UserRoleId = userRoles;
            }
        }
    }
}

PresentationLayer/Areas/Admin/Controllers/PaymentRecordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentationLayer.Areas.Admin.Controllers
{
    public class PaymentRecordsController : Controller
    {
        // GET: Admin/PaymentRecords
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UnpaidMonths()
        {
            return View();
        }
    }
}

PresentationLayer/Areas/Admin/Controllers/PensionerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PresentationLayer.Models;
using ModelLayer;
using BusinessLayer;
using PresentationLayer.Controllers;
using PresentationLayer.Areas.Admin.ViewModels;

namespace PresentationLayer.Areas.Admin.Controllers
{
    public class PensionerController : BaseController
    {
        // GET: Admin/Pensioner
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            ViewBag.Title = string.Format("Welcome {0} | View All Pensioners", DoesCookieExist("Username") ? GetHttpCookie("Username") : "Admin");
            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult ViewPensioners()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AddPensioner()
        {
            ViewBag.Title = string.Format("Add Pensioner | {0}", DoesCookieExist("Username") ? GetHttpCookie("Username") : "Admin");
            return View();
        }
        //Fill Select Options
        //BaseController: Upload File
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult AddPensioner(AddPensionerViewModel model)
        {
            try
            {              
                throw new Exception("Model Seems to work");
            }
            catch(Exception ex) { throw ex; }

            return View();
        }

        public ActionResult EmploymentData()
        {
            return View();
        }

        public ActionResult BankData()
        {
            return View();
        }

        public ActionResult OriginData()
        {
            return View();
        }

        public ActionResult PersonalData()
        {
            return View();
        }

        public ActionResult NextOfKinData()
        {
            return View();
        }

        public ActionResult EditPersonalData()
        {
            return View();
        }

        public ActionResult EditOriginData()
        {
            return View();
        }

        public ActionResult EditEmploymentData()
        {
            return View();
        }

        public ActionResult EditBankData()
        {
            return View();
        }

        public ActionResult EditNextOfKinData()
        {
            return View();
        }

        public ActionResult AllDetails()
        {
            return View();
        }

    }
}

PresentationLayer/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Manage Pensioners", "Index", "Pensioner", new { Area = "Admin" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="" class="dropdown-toggle" type="button" data-toggle="dropdown" id="dropdownMenu1">
                            Manage Pensioners
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                            <li role="presentation">
                                <a href="@Url.Action("Index", "Pensioner")" role="menuitem" tabindex="-1">View All</a>
                            </li>
                            <li role="presentation">
                                <a href="@Url.Action("AddPensioner", "Pensioner")" role="menuitem" tabindex="-1">Add Pensioner</a>
                            </li>
                        </ul>
                    </li>
                    @*<li>@Html.ActionLink("Manage Pensioners", "Manage", "Pensioner", new { Area = "Admin" }, null)</li>*@
                    <li>
                        <a href="" class="dropdown-toggle" type="button" data-toggle="dropdown" id="dropdownMenu2">
                             Account
                            <span class="caret"></span>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                                <li role="presentation">
                                    <a href="@Url.Action("Index", "ManageAccount")" role="menuitem" tabindex="-1">Change Credentials</a>
                                </li>
                                <li role="presentation">
                                    <a href="@Url.Action("AddNewAdmin", "ManageAccount")" role="menuitem" tabindex="-1">Add New Admin</a>
                                </li>
                            </ul>
                        </a>
                    </li>
                    <li>
                        <a href="" class="dropdown-toggle" type="button" data-toggle="dropdown" id="dropdownMenu1">
                           Payment Records
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                            <li role="presentation">
                                <a href="@Url.Action("Index", "PaymentRecords")" role="menuitem" tabindex="-1">Paid Months</a>
                            <li role="presentation">
                                <a href="@Url.Action("UnpaidMonths", "PaymentRecords")" role="menuitem" tabindex="-1">Unpaid Months</a>
                            </li>
                            </li>
                        </ul>
                    </li>
                </ul>
                <div class="navbar-right">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Logout", "LogOff", "Account", new { Area = "Security" }, null)</li>
                    </ul>
                </div>
                  
                </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>